### ISSUE TITLE
Fix Home Page on AppCenter

### ISSUE THREAD

**Issue by btd1337** [Alecaddd/taxi#45]
In the App Center, the application home page is directed to the Sequeler project. Is it possible to fix this?

[In this file](https://github.com/Alecaddd/taxi/blob/master/data/com.github.alecaddd.taxi.appdata.xml.in) is correct but in Appcenter doesn't.

**Comment by Alecaddd** [comment]
Thanks for reporting the issue, I'll fix it in the next release

**Comment by rajkumaar23** [comment]
@Alecaddd why is the homepage still pointing to sequeler?

**Comment by danrabbit** [comment]
Fixed in https://github.com/Alecaddd/taxi/commit/892082deabff8d2ad5927eb1b7491c2fb29008ef
